pub mod acp;
pub mod agent_setup;
pub mod agent_skills;
pub mod agents;
pub mod artifacts;
#[cfg_attr(not(feature = "block-builderbot"), allow(dead_code))]
pub mod auth;
#[cfg(feature = "block-automations")]
pub mod automations;
pub mod avatars;
#[cfg(feature = "block-builderbot")]
pub mod builderbot;
pub mod cache;
#[cfg(feature = "block-agent-tools")]
pub mod cli;
#[cfg(feature = "block-managed-connections")]
pub mod connections;
pub mod diagnostics;
pub mod distro;
#[cfg_attr(not(feature = "block-feedback"), allow(dead_code))]
pub mod doctor;
#[cfg(feature = "block-feedback")]
pub mod feedback;
pub mod feedback_survey;
pub mod git;
pub mod git_changes;
pub mod global_shortcut;
pub mod home_widget_media;
pub mod installation;
pub mod layout;
pub mod local_mcp_inventory;
pub mod mac_speech;
pub mod message_queues;
pub mod microphone_permission;
pub mod migration;
pub mod model_setup;
mod native_input_mute;
pub mod native_voice;
pub mod notifications;
pub mod openai_audio;
#[cfg(feature = "block-voice-dictation")]
pub mod openai_realtime;
mod openai_voice_credentials;
pub mod path_resolver;
#[cfg(target_os = "macos")]
mod pocket_audio_player;
pub mod pocket_voice;
pub mod pr_tracker;
pub mod project_icons;
pub mod pull_requests;
pub mod renderer;
pub mod runtime_config;
pub mod security_threshold;
pub mod siri_voice;
#[cfg(feature = "block-skill-discovery")]
pub mod skill_marketplace;
pub mod system;
pub mod telemetry;
pub mod terminal;
pub mod updates;
pub mod voice_buddy;
pub mod voice_capture;
pub mod whoami;
pub mod window_session;
pub mod workspace_context;
