import type { AcpProvider } from "@/shared/api/acp";
import type { ProviderCatalogEntry } from "@/shared/types/providers";

export const CURATED_PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "goose",
    displayName: "Goose",
    category: "agent",
    description: "Block's open-source coding agent",
    setupMethod: "none",
    group: "default",
    aliases: ["goose"],
  },
  {
    id: "claude-acp",
    displayName: "Claude Code",
    category: "agent",
    description: "Anthropic's agentic coding tool",
    setupMethod: "cli_auth",
    binaryName: "claude-agent-acp",
    group: "default",
    aliases: ["claude-acp", "claude_code", "claude-code", "claude"],
    supportsInstall: true,
    supportsAuth: true,
    supportsAuthStatus: true,
    bundledBridge: true,
  },
  {
    id: "codex-acp",
    displayName: "Codex",
    category: "agent",
    description: "OpenAI's coding agent",
    setupMethod: "cli_auth",
    binaryName: "codex-acp",
    group: "default",
    aliases: ["codex-acp", "codex_cli", "codex-cli", "codex"],
    supportsInstall: true,
    supportsAuth: true,
    supportsAuthStatus: true,
    bundledBridge: true,
  },
  {
    id: "copilot-acp",
    displayName: "Copilot",
    category: "agent",
    description: "GitHub Copilot coding agent",
    setupMethod: "cli_auth",
    binaryName: "copilot",
    group: "default",
    aliases: ["copilot-acp", "copilot"],
    supportsInstall: true,
    supportsAuth: true,
    supportsAuthStatus: false,
  },
  {
    id: "amp-acp",
    displayName: "Amp",
    category: "agent",
    description: "Sourcegraph Amp coding agent",
    setupMethod: "cli_auth",
    binaryName: "amp-acp",
    group: "default",
    aliases: ["amp-acp", "amp"],
    supportsInstall: true,
    supportsAuth: true,
    supportsAuthStatus: true,
    supportsModelList: false,
    modelSelectionHint: "Use the Amp CLI to configure the model.",
  },
  {
    id: "cursor-agent",
    displayName: "Cursor Agent",
    category: "agent",
    description: "Cursor command-line agent",
    setupMethod: "cli_auth",
    binaryName: "cursor-agent",
    group: "default",
    aliases: ["cursor-agent", "cursor"],
    supportsInstall: true,
    supportsAuth: true,
    supportsAuthStatus: true,
  },
  {
    id: "pi-acp",
    displayName: "Pi",
    category: "agent",
    description: "Pi coding agent",
    setupMethod: "cli_auth",
    binaryName: "pi-acp",
    group: "default",
    aliases: ["pi-acp", "pi"],
    supportsInstall: false,
    supportsAuth: false,
    supportsAuthStatus: false,
  },
  {
    id: "databricks_v2",
    displayName: "Databricks AI Gateway",
    category: "model",
    description: "Databricks AI Gateway models",
    setupMethod: "host_with_oauth_fallback",
    nativeConnectQuery: "databricks",
    group: "default",
    aliases: ["databricks_v2", "databricks", "databricks-ai-gateway"],
    supportsInstall: false,
    supportsAuth: false,
    supportsAuthStatus: false,
  },
];

export const CURATED_PROVIDER_CATALOG_BY_ID = new Map(
  CURATED_PROVIDER_CATALOG.map((provider) => [provider.id, provider]),
);

export function getCuratedAgentProviders(): AcpProvider[] {
  return CURATED_PROVIDER_CATALOG.filter(
    (provider) => provider.category === "agent",
  ).map((provider) => ({ id: provider.id, label: provider.displayName }));
}
